# Generated by Django 6.0.4 on 2026-04-12 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('laboratory', 'Laboratory'), ('classroom', 'Classroom'), ('conference', 'Conference Room'), ('auditorium', 'Auditorium'), ('other', 'Other')], default='classroom', max_length=30),
        ),
        migrations.AddField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='tags',
            field=models.CharField(blank=True, help_text='e.g. AV-enabled, conference room', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('facility_manager', 'Facility Manager'), ('technical_staff', 'Technical Staff'), ('standard_user', 'Standard User')], default='standard_user', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('approval', 'Booking Approved'), ('rejection', 'Booking Rejected'), ('reminder', 'Booking Reminder'), ('cancellation', 'Booking Cancelled'), ('announcement', 'Announcement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
