# Generated by Django 6.0.4 on 2026-04-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_booking_options_remove_facility_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['building', 'floor', 'name'], 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='facility',
            name='availability_end',
            field=models.TimeField(blank=True, help_text='Default available until', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='availability_start',
            field=models.TimeField(blank=True, help_text='Default available from', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='building',
            field=models.CharField(blank=True, default='CAS Building', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='custodian',
            field=models.CharField(blank=True, help_text='Name of assigned custodian/owner', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='floor',
            field=models.CharField(blank=True, choices=[('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('3rd Floor', '3rd Floor'), ('4th Floor', '4th Floor'), ('5th Floor', '5th Floor'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
