# Generated by Django 6.0.4 on 2026-04-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_facility_options_facility_availability_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='allowed_roles',
            field=models.CharField(blank=True, help_text='Comma-separated roles that can book this facility', max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If true, only allowed roles/users can book'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science'), ('BSIS', 'BS Information Systems'), ('IT_DEPT', 'IT Department'), ('ADMIN', 'Administration'), ('OTHER', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_notes',
            field=models.TextField(blank=True, help_text='Additional notes about this user'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='availability_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='availability_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='custodian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('book', 'Created Booking'), ('cancel', 'Cancelled Booking'), ('create_facility', 'Created Facility'), ('edit_facility', 'Edited Facility'), ('approve', 'Approved Booking'), ('reject', 'Rejected Booking'), ('create_user', 'Created User'), ('edit_user', 'Edited User')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
