# Generated by Django 6.0.4 on 2026-04-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_facility_allowed_roles_facility_is_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='apps.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='allowed_roles',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('approval', 'Booking Approved'), ('rejection', 'Booking Rejected'), ('reminder', 'Booking Reminder'), ('cancellation', 'Booking Cancelled'), ('announcement', 'Announcement'), ('escalation', 'Escalation Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target_roles', models.CharField(blank=True, help_text='Blank = all users', max_length=200)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('confirmation', 'Booking Confirmation'), ('approval', 'Booking Approved'), ('rejection', 'Booking Rejected'), ('reminder', 'Booking Reminder'), ('cancellation', 'Booking Cancelled'), ('announcement', 'Announcement'), ('escalation', 'Escalation Alert')], max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Variables: {user}, {facility}, {date}, {start_time}, {end_time}, {status}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
            },
        ),
    ]
