# Generated by Django 6.0.4 on 2026-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
