# Generated by Django 6.0.4 on 2026-04-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_issuereport_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='issue_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='apps.issuereport'),
        ),
    ]
