# Generated by Django 6.0.4 on 2026-05-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_notification_issue_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
