# Generated by Django 6.0.4 on 2026-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_user_security_answer_user_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='department',
            field=models.CharField(blank=True, choices=[('BSIT', 'BS Information Technology'), ('BSCS', 'BS Computer Science'), ('BSIS', 'BS Information Systems'), ('IT_DEPT', 'IT Department'), ('ADMIN', 'Administration'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('key', 'department')},
        ),
    ]
